FROM node:20-alpine
 
WORKDIR /user/src/app
 
COPY --chown=node:node package*.json ./
 
RUN npm ci
 
COPY --chown=node:node . .

RUN npm run build
RUN npm install -g serve

USER node
 
CMD ["serve", "-s", "build", "-l", "3000"]