name: Master Deploy Workflow
on: 
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Deploy master branch to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ghactions/master 
            echo ${{ secrets.SUDO_PSWD }} | sudo -S git pull origin master
            sudo -S docker compose build