name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code!
        uses: actions/checkout@v3
      - name: Install backend dependencies
        run: 
          cd backend
          npm install
          npm run test