name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code!
        uses: actions/checkout@v4
      #- name: Goto backend folder
      #  run: cd backend
      #- name: Установка Node.js
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '20'
      #- name: Install backend dependencies
      #  run: npm install --prefix backend
      #- name: Run backend tests
      #  run: npm run test --prefix backend
      #- name: Add secrets to envirnment.
      #  env:
      #   POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      #    POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      #    POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      #    PGADMIN_DEFAULT_EMAIL: ${{secrets.PGADMIN_DEFAULT_EMAIL}}
      #    PGADMIN_DEFAULT_PASSWORD: ${{secrets.PGADMIN_DEFAULT_PASSWORD}}
      #    DB_HOST: ${{secrets.DB_HOST}}
      #    DB_PORT: ${{secrets.DB_PORT}}
      #    DB_USERNAME: ${{secrets.DB_USERNAME}}
      #    DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      #    REDIS_HOST: ${{secrets.REDIS_HOST}}
      #    REDIS_PORT: ${{secrets.REDIS_PORT}}
      #    TTL: ${{secrets.TTL}}
      #    DEFAULT_ADMIN_NAME: ${{secrets.DEFAULT_ADMIN_NAME}}
      #    DEFAULT_ADMIN_EMAIL: ${{secrets.DEFAULT_ADMIN_EMAIL}}
      #    DEFAULT_ADMIN_PASSWORD: ${{secrets.DEFAULT_ADMIN_PASSWORD}}
      #    JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      #    JWT_EXPIRATION_TIME: ${{secrets.JWT_EXPIRATION_TIME}}
      #  run: |
      #    docker-compose -f docker-compose-github-actions.yml pull
      - name: Create a dummy file on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ghactions/dev 
            echo ${{ secrets.SUDO_PSWD }}
            sudo -S git pull origin dev